# Example: SAS SWAT - Train a Decision Tree Classifier
This example trains a Decision Tree Classifier on the IRIS dataset and scores the data.

In [1]:
# Connect to SAS Viya Platform
import swat
conn = swat.CAS(hostname='localhost', port=5570, username='sas', password='saspw')

In [2]:
# Load Dataset from local CSV file
iris = conn.read_csv('data/iris.csv', casout=dict(name='iris', caslib='casuser'))
iris.head()

NOTE: Cloud Analytic Services made the uploaded file available as table IRIS in caslib CASUSER(sas).
NOTE: The table IRIS has been created in caslib CASUSER(sas) from binary data uploaded to Cloud Analytic Services.

Selected Rows from Table IRIS

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
# Load Decision Tree functionalities and train a Decision Tree Classifier
conn.loadactionset('decisiontree')
tree_model = iris.Dtreetrain()
tree_model.target = 'species'
tree_model.inputs = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
tree_model.casout = 'iris_dtree'
tree_model()

NOTE: Added action set 'decisiontree'.

[ModelInfo]

 Decision Tree for IRIS

                            Descr       Value
 0           Number of Tree Nodes   11.000000
 1         Max Number of Branches    2.000000
 2               Number of Levels    5.000000
 3               Number of Leaves    6.000000
 4                 Number of Bins   50.000000
 5         Minimum Size of Leaves    5.000000
 6         Maximum Size of Leaves   50.000000
 7            Number of Variables    4.000000
 8   Confidence Level for Pruning    0.250000
 9    Number of Observations Used  150.000000
 10   Misclassification Error (%)    2.666667

[OutputCasTables]

          casLib        Name  Rows  Columns  \
 0  CASUSER(sas)  iris_dtree    11       25

                                         casTable
 0  CASTable('iris_dtree', caslib='CASUSER(sas)')

+ Elapsed: 0.0166s, user: 0.0137s, sys: 0.0178s, mem: 21.7mb

In [11]:
# Score the dataset with the trained model
iris.dtreescore(assess=False, 
                model=tree_model.casout, 
                copyVars=list(iris.columns),
                casout=dict(name='iris_dtree_scored', replace=True))

[OutputCasTables]

          casLib               Name  Rows  Columns  \
 0  CASUSER(sas)  iris_dtree_scored   150       16

                                             casTable
 0  CASTable('iris_dtree_scored', caslib='CASUSER(...

[ScoreInfo]

                          Descr                             Value
 0  Number of Observations Read                               150
 1  Number of Observations Used                               150
 2  Misclassification Error (%)                      2.6666666667

+ Elapsed: 0.00382s, user: 0.00659s, mem: 26mb

In [12]:
# Display Scoring results
conn.CASTable('iris_dtree_scored')[list(iris.columns)+['_DT_PredName_']].tail(10)

,sepal_length,sepal_width,petal_length,petal_width,species,_DT_PredName_
140,6.1,2.6,5.6,1.4,Iris-virginica,Iris-virginica
141,7.7,3.0,6.1,2.3,Iris-virginica,Iris-virginica
142,6.3,3.4,5.6,2.4,Iris-virginica,Iris-virginica
143,6.4,3.1,5.5,1.8,Iris-virginica,Iris-virginica
144,6.0,3.0,4.8,1.8,Iris-virginica,Iris-virginica
145,6.9,3.1,5.4,2.1,Iris-virginica,Iris-virginica
146,6.7,3.1,5.6,2.4,Iris-virginica,Iris-virginica
147,6.9,3.1,5.1,2.3,Iris-virginica,Iris-virginica
148,5.8,2.7,5.1,1.9,Iris-virginica,Iris-virginica
149,6.8,3.2,5.9,2.3,Iris-virginica,Iris-virginica